import 'package:flutter_frontend/data/models/question_category.dart';

// Preguntas organizadas por tipo de relación del memorial.
// Si más adelante quieres soportar internacionalización, puedes
// extraer estas listas a un servicio o a ARB/JSON.

final List<QuestionCategory> questionsCategories = [
  QuestionCategory(
    name: 'FAMILIA',
    questions: [
      '¿Cuál es el primer recuerdo que tienes con esta persona?',
      '¿Qué canción asocias con ella?',
      '¿Cómo era un día típico en casa cuando estaban juntos?',
      '¿Qué tradición familiar iniciada por esa persona recuerdas con más cariño?',
      '¿Cuál fue la lección más valiosa que te enseñó?',
      '¿Qué costumbre suya extrañas más?',
      '¿Qué momento de orgullo familiar compartieron juntos?',
      '¿Qué lugar de la casa te hace pensar inmediatamente en esa persona?',
      '¿Qué objeto pequeño conservas (o conservarías) como recuerdo de ella?',
      '¿Cómo celebraban los cumpleaños o las fiestas en familia?',
      '¿Qué tradición te gustaría mantener para honrar su legado?',
      '¿Qué consejo suyo aplicas hoy en tu vida diaria?',
      '¿Cuál fue el mejor viaje o salida familiar que hicieron juntos?',
      '¿Cómo se resolvían los problemas familiares cuando ella estaba presente?',
      '¿Qué gesto afectuoso suyo recuerdas con especial cariño?',
      '¿Qué plato o receta cocinarías para revivir un momento con esa persona?',
      '¿Qué historia de tu infancia sobre ustedes dos se repite siempre en la familia?',
      '¿Qué cambio importante en tu vida ocurrió por influencia de esa persona?',
      '¿Qué actividad cotidiana solían compartir?',
      '¿Cómo te gustaría que las futuras generaciones la recuerden?'
    ],
  ),
  QuestionCategory(
    name: 'AMIGOS',
    questions: [
      '¿Cómo y dónde se conocieron?',
      '¿Cuál fue la primera salida o plan que recuerdas con esa persona?',
      '¿Cuál fue la travesura o momento más inolvidable que vivieron juntos?',
      '¿Qué canción, playlist o estilo musical te recuerda a esa amistad?',
      '¿Qué te enseñó sobre la verdadera amistad?',
      '¿Cuál fue el momento más difícil que superaron juntos?',
      '¿En qué lugar pasaban más tiempo?',
      '¿Cuál fue el mejor consejo que te dio?',
      '¿Qué restaurante, café o sitio frecuente usaban para conversar?',
      '¿Cuál es la anécdota más graciosa que comparten?',
      '¿Qué rutina compartida te gustaría retomar?',
      '¿Qué regalo o detalle memorable se dieron?',
      '¿Qué te enseñó sobre la lealtad?',
      '¿Qué discusión o conflicto fortaleció su vínculo?',
      '¿Qué película o serie solían recomendarse mutuamente?',
      '¿Qué frase o muletilla te hace pensar inmediatamente en esa persona?',
      '¿Qué proyecto o sueño compartieron (aunque no se concretara)?',
      '¿Qué virtud suya intentas imitar?',
      '¿Qué momento te hizo sentir que confiabas plenamente en esa persona?',
      'Si pudieras revivir una tarde juntos, ¿qué harían?'
    ],
  ),
  QuestionCategory(
    name: 'PAREJA',
    questions: [
      '¿Cómo y dónde se conocieron?',
      '¿En qué momento sentiste que era amor?',
      '¿Qué gesto suyo te hacía sentir seguro(a) o amado(a)?',
      '¿Cuál es el recuerdo más tierno que guardas de la relación?',
      '¿Qué canción era la de ustedes para bailar, cantar o dedicar?',
      '¿Cuál fue la cita más especial que tuvieron?',
      '¿Qué rutina diaria compartían que hoy extrañas?',
      '¿Cuál fue el momento más divertido que vivieron?',
      '¿Qué aprendiste sobre el amor gracias a esa persona?',
      '¿Qué apodo especial se tenían?',
      '¿Qué pequeño detalle suyo siempre notabas y apreciabas?',
      '¿Qué tradición festejaban como pareja?',
      '¿Qué aprendiste sobre la confianza a partir de esa relación?',
      '¿Qué viaje juntos te marcó y por qué?',
      '¿Qué aspecto de su personalidad admirabas más?',
      '¿Cuál fue el mejor regalo (material o simbólico) que intercambiaron?',
      '¿Qué objeto asocias inmediatamente con la relación y por qué?',
      '¿Qué recuerdo te ayuda a sonreír en días difíciles?',
      '¿Qué promesa compartida recuerdas con nostalgia?',
      '¿Cómo deseas honrar esa relación en tu vida actual?'
    ],
  ),
  QuestionCategory(
    name: 'MASCOTA',
    questions: [
      '¿Cómo llegó a tu vida?',
      '¿Qué recuerdas del primer día juntos que te haga sonreír?',
      '¿Qué rutina diaria compartían?',
      '¿Qué travesura hacía que te impedía enojarte de verdad?',
      '¿Cuál era su juguete o juego favorito?',
      '¿Cómo te acompañaba en los días difíciles?',
      '¿Cuál era su lugar favorito de la casa?',
      '¿Cuál era su comida o premio favorito?',
      '¿Cuál es la anécdota más graciosa que recuerdas?',
      '¿Qué truco o habilidad tenía que te sorprendiera?',
      '¿Qué objeto conservas (o conservarías) como recuerdo?',
      '¿Qué hacía al llegar tú a casa que te alegraba el día?',
      '¿Qué rasgo de su personalidad extrañas más?',
      '¿Cómo celebrabas su cumpleaños o momentos especiales?',
      '¿Qué le dirías si pudieras volver a acariciarlo(a)?',
      '¿Qué haces o te gustaría hacer para mantener viva su memoria?',
      '¿Qué momento recuerdas que resume su personalidad?',
      '¿Qué sonido (ladrido, ronroneo, etc.) extrañas más?',
      '¿Qué aprendiste sobre el cariño y el cuidado gracias a ella/él?',
      '¿Cómo la(o) describirías a alguien que nunca la(o) conoció?'
    ],
  ),
  QuestionCategory(
    name: 'OTRO',
    questions: [
      '¿Quién era esa persona y cómo entró en tu vida?',
      '¿Cuál de sus cualidades admirabas más y por qué?',
      '¿Qué enseñanza o idea suya te marcó profundamente?',
      '¿En qué momento sentiste que su influencia provocó un cambio en ti?',
      '¿Qué libro, frase o fragmento asociado a ella recuerdas con fuerza?',
      '¿Qué pregunta te habría gustado hacerle en persona?',
      '¿Qué acto de valor o coherencia suya te impresionó más?',
      '¿Qué historia o “mito” sobre esa persona te intriga todavía?',
      '¿Qué le agradecerías hoy si pudieras hablarle?',
      '¿Qué proyecto o idea suya impactó tu vocación o carrera?',
      '¿Qué similitud encuentras entre tu vida y la suya?',
      '¿Qué objeto, lugar o detalle cotidiano asocias inmediatamente con esa persona?',
      '¿Qué impacto crees que tuvo en su comunidad o entorno cercano?',
      '¿Qué consejo suyo aplicaste que cambió tu rumbo?',
      '¿Qué pregunta crees que esa persona te haría hoy a ti?',
      '¿Cómo te gustaría honrar su memoria o legado?',
      '¿Qué acto simbólico consideras adecuado para recordarla?',
      '¿Qué foto, testimonio o evidencia te gustaría preservar de esa persona?',
      '¿Qué aspecto de su pensamiento te inspira a seguir explorando?',
      '¿Qué mensaje te gustaría transmitir a otros sobre quién fue y lo que representó?'
    ],
  ),
];
